---
deployment:
  tasks:
    - export DEPLOYPATH=/home/amaw5221/public_html/
    - export APPPATH=/home/amaw5221/amado/
    - /bin/mv .env.example .env $APPPATH
    - /bin/mv -R public $DEPLOYPATH
    - /bin/mv -a * $APPPATH
    